version: 2.1
jobs:
  Export-Project:
    steps:
      - run:
          name: script is not currently supported.
          command: exit 1
          JFC_STACK_TRACE: |-
            script if ( DEBUG_FLG.toBoolean() ) {
                        env.EXEC_METHOD = EXECUTE_DEBUG_METHOD
                      } else {
                        env.EXEC_METHOD = EXECUTE_METHOD
                      }
      - run: 'rm -rf ${EXPORT_PATH}/*'
        working_directory: '${STAGE_DIR}'
      - run:
          name: |
            Keyword not recognized
          command: exit 1
          JFC_STACK_TRACE: |-
            Please refer to CircleCI documentation (https://circleci.com/docs/reference-2-1/#section=configuration)
            and/or submit an issue at https://github.com/circleci/jenkinsfile-convertor
            checkout ${scm}
        working_directory: '${STAGE_DIR}'
      - run: |2-

                      ${UNITY} -quit                      -batchmode                      -projectPath ${PWD}                      -buildTarget android                      -logFile '/dev/stdout'                      -executeMethod ${EXEC_METHOD}

        working_directory: '${STAGE_DIR}'
    executor: cimg/base
  Android-Build:
    steps:
      - run:
          name: |
            Keyword not recognized
          command: exit 1
          JFC_STACK_TRACE: |-
            Please refer to CircleCI documentation (https://circleci.com/docs/reference-2-1/#section=configuration)
            and/or submit an issue at https://github.com/circleci/jenkinsfile-convertor
            checkout ${scm}
        working_directory: '${STAGE_DIR}'
      - run:
          name: |
            Keyword not recognized
          command: exit 1
          JFC_STACK_TRACE: |-
            Please refer to CircleCI documentation (https://circleci.com/docs/reference-2-1/#section=configuration)
            and/or submit an issue at https://github.com/circleci/jenkinsfile-convertor
            unstash project
        working_directory: '${STAGE_DIR}'
      - run: 'unzip -o ${EXPORT_PATH}.zip'
        working_directory: '${STAGE_DIR}'
      - run: |2-

                      cd "${EXPORT_PATH}/${PRODUCT_NAME}"

                      chmod +x ./local.properties
                      rm -rf ./local.properties
                      echo ndk.dir=${ANDROID_NDK_HOME} >> ./local.properties
                      echo sdk.dir=${ANDROID_SDK_HOME} >> ./local.properties

                      ../../android_project/gradlew clean assembleRelease

        working_directory: '${STAGE_DIR}'
      - run: |2-

                      rm -rf ${RESULT_DIR}
                      mkdir -p ${RESULT_DIR}
                      mv ${EXPORT_PATH}/${PRODUCT_NAME}/build/outputs/apk/*/*.apk ${RESULT_DIR}
                      mv ${EXPORT_PATH}/${PRODUCT_NAME}/build/intermediates/jniLibs/* ${RESULT_DIR}
                      zip -r ${RESULT_ZIP_FILE} ${RESULT_DIR}

        working_directory: '${STAGE_DIR}'
    executor: cimg/base
workflows:
  version: 2
  build-and-test:
    jobs:
      - Export-Project
      - Android-Build:
          requires: Export-Project