version: 2.1

jobs:
  build-and-unit-test:
    docker:
      - image: circleci/node:12.8.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: run unit tests
          command: npm test
  
  generate-configs:
    docker:
      - image: circleci/node:12.8.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: create artifacts dir
          command: mkdir -p ~/project/artifacts          
      - run:
          name: create config.yml
          command: ~/project/test/createConfigs.sh
      - store_artifacts:
          path: ~/project/artifacts
      - persist_to_workspace:
          root: ~/project
          paths:
            - artifacts/
            - test/validateConfigs.sh
  
  output-smoke-test:
    docker:
      - image: circleci/node:12.8.0
    working_directory: ~/project
    steps:
      - run:
          name: install CircleCI CLI
          command: curl -fLSs https://circle.ci/cli | sudo bash
      - attach_workspace:
          at: ~/project
      - run:
          name: validate configs
          command: ~/project/test/validateConfigs.sh

workflows:
  version: 2
  btd:
    jobs:
      - build-and-unit-test
      - generate-configs:
          requires:
            - build-and-unit-test
      - output-smoke-test:
          requires:
            - generate-configs

